-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 23:39:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mxmaf_01es
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mxmaf_01es
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mxmaf_01es` DEFAULT CHARACTER SET utf8 ;
USE `mxmaf_01es` ;

-- -----------------------------------------------------
-- Table `mxmaf_01es`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `firtsname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mxmaf_01es`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mxmaf_01es`.`type_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`type_contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mxmaf_01es`.`contact_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`contact_item` (
  `id` INT NOT NULL,
  `type_contact` INT NOT NULL,
  `user` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  INDEX `fk_contact_item_type_contact_idx` (`type_contact` ASC),
  INDEX `fk_contact_item_user1_idx` (`user` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_contact_item_type_contact`
    FOREIGN KEY (`type_contact`)
    REFERENCES `mxmaf_01es`.`type_contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_item_user1`
    FOREIGN KEY (`user`)
    REFERENCES `mxmaf_01es`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mxmaf_01es`.`user_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`user_device` (
  `device_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`device_id`, `user_id`),
  INDEX `fk_device_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_device_has_user_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_device_has_user_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `mxmaf_01es`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mxmaf_01es`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mxmaf_01es`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`log` (
  `id` INT NOT NULL,
  `device_id` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `devicedata` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_log_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_log_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `mxmaf_01es`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mxmaf_01es`.`type_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`type_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mxmaf_01es`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mxmaf_01es`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_id` INT NOT NULL,
  `type_event_id` INT NOT NULL,
  `log_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_status1_idx` (`status_id` ASC),
  INDEX `fk_event_type_event1_idx` (`type_event_id` ASC),
  INDEX `fk_event_log1_idx` (`log_id` ASC),
  CONSTRAINT `fk_event_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `mxmaf_01es`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_type_event1`
    FOREIGN KEY (`type_event_id`)
    REFERENCES `mxmaf_01es`.`type_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_log1`
    FOREIGN KEY (`log_id`)
    REFERENCES `mxmaf_01es`.`log` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mxmaf_01es`.`notifications_conf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mxmaf_01es`.`notifications_conf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact_item_id` INT NOT NULL,
  `type_event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notifications_conf_contact_item1_idx` (`contact_item_id` ASC),
  INDEX `fk_notifications_conf_type_event1_idx` (`type_event_id` ASC),
  CONSTRAINT `fk_notifications_conf_contact_item1`
    FOREIGN KEY (`contact_item_id`)
    REFERENCES `mxmaf_01es`.`contact_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_conf_type_event1`
    FOREIGN KEY (`type_event_id`)
    REFERENCES `mxmaf_01es`.`type_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
